[package]
name = "tg-rcore-tutorial-multi-processor-console-wzy"
description = "Provides `print!`, `println!` and `log::Log` with customizable implementations for rCore tutorial, with SMP support."
version = "0.1.0-preview.1"
edition = "2024"
authors = ["Ziyan Wang <charliewang.cpp@gmail.com>"]
repository = "https://github.com/CharlieVinnie/tg-rcore-tutorial"
homepage = "https://github.com/CharlieVinnie/tg-rcore-tutorial/tree/smp"
documentation = "https://docs.rs/tg-rcore-tutorial-console"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded"]

[dependencies]
log = "0.4"
spin = "0.9"
