[package]
name = "tg-rcore-tutorial-games-ch3-snake-kernel"
edition = "2024"
version = "0.1.0-preview.1"
authors = ["Ziyan Wang <charliewang.cpp@gmail.com>"]
description = "Kernel support for game of ch3 of tg-rcore tutorial"
repository = "https://github.com/CharlieVinnie/tg-rcore-tutorial"
license = "GPL-3.0"
readme = "README.md"
keywords = [
    "ai",
    "ai4ose",
    "kernel",
    "learning",
    "os",
]
categories = [
    "no-std",
    "embedded",
]

[features]
"coop" = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
riscv = "0.10.1"
spin = "0.9"
buddy_system_allocator = "0.9"

tg-sbi = { package = "tg-rcore-tutorial-sbi", version = "0.4.5", features = ["nobios"] }
tg-linker = { package = "tg-rcore-tutorial-linker", version = "0.4.5" }
tg-console = { package = "tg-rcore-tutorial-console", version = "0.4.5" }
tg-kernel-context = { package = "tg-rcore-tutorial-kernel-context", version = "0.4.5" }
tg-syscall = { package = "tg-rcore-tutorial-games-syscall", version = "0.1.0-preview.1", features = ["kernel"] }
tg-driver = { package = "tg-rcore-tutorial-driver", version = "0.1.0-preview.1" }

[build-dependencies]
tg-linker = { package = "tg-rcore-tutorial-linker", version = "0.4.5" }