[package]
name = "tg-rcore-tutorial-games"
version = "0.1.0"
edition = "2024"
description = "User-space games for rCore Tutorial"

[lib]
name = "games_lib"
path = "src/lib.rs"

[dependencies]
tg-console = { package = "tg-rcore-tutorial-console", path = "../tg-rcore-tutorial-console", version = "0.4.2-preview.7" }
tg-syscall = { package = "tg-rcore-tutorial-syscall", path = "../tg-rcore-tutorial-syscall", version = "0.4.2-preview.7", features = ["user"] }
customizable-buddy = "0.0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
