[package]
name = "tg-rcore-tutorial-games-ch5-pingpong-kernel"
edition = "2024"
version = "0.1.0-preview.3"
authors = ["Ziyan Wang <charliewang.cpp@gmail.com>"]
description = "Kernel support for game of ch5 of tg-rcore tutorial"
repository = "https://github.com/CharlieVinnie/tg-rcore-tutorial"
homepage = "https://github.com/CharlieVinnie/tg-rcore-tutorial/tree/game"
changelog = "https://github.com/CharlieVinnie/tg-rcore-tutorial/tree/game/tg-rcore-tutorial-ch5/CHANGELOG.md"
license = "GPL-3.0"
readme = "README.md"
keywords = [
    "ai",
    "ai4ose",
    "kernel",
    "learning",
    "os",
]
categories = [
    "no-std",
    "embedded",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
xmas-elf = "0.8.0"
riscv = "0.10.1"
spin = "0.9"

tg-sbi = { package = "tg-rcore-tutorial-sbi", version = "0.4.5", features = ["nobios"] }
tg-linker = { package = "tg-rcore-tutorial-linker", version = "0.4.5" }
tg-console = { package = "tg-rcore-tutorial-console", version = "0.4.5" }
tg-kernel-context = { package = "tg-rcore-tutorial-kernel-context", version = "0.4.5", features = ["foreign"] }
tg-syscall = { package = "tg-rcore-tutorial-games-syscall", version = "0.1.0-preview.3", features = ["kernel"] }
tg-kernel-alloc = { package = "tg-rcore-tutorial-kernel-alloc", version = "0.4.5" }
tg-kernel-vm = { package = "tg-rcore-tutorial-games-kernel-vm", version = "0.1.0-preview.1" }
tg-driver = { package = "tg-rcore-tutorial-driver", version = "0.1.0-preview.1" }
tg-task-manage = { package = "tg-rcore-tutorial-task-manage", version = "0.4.5", features = ["proc"] }

[build-dependencies]
tg-linker = { package = "tg-rcore-tutorial-linker", version = "0.4.5" }