[package]
name = "tg-rcore-tutorial-games-ch1-tangram-kernel"
edition = "2024"
version = "0.1.0-preview.1"
authors = ["Ziyan Wang <charliewang.cpp@gmail.com>"]
description = "Kernel support for game of ch1 of tg-rcore tutorial"
repository = "https://github.com/CharlieVinnie/tg-rcore-tutorial"
license = "GPL-3.0"
readme = "README.md"
keywords = [
    "ai",
    "ai4ose",
    "kernel",
    "learning",
    "os",
]
categories = [
    "no-std",
    "embedded",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
spin = "0.9"
tg-sbi = { package = "tg-rcore-tutorial-sbi", version = "0.4.5", features = ["nobios"] }
riscv = "0.11"
virtio-drivers = "0.1.0"
tg-driver = { package = "tg-rcore-tutorial-driver", version = "0.1.0-preview.1" }
buddy_system_allocator = "0.9"
