[package]
name = "tg-rcore-tutorial-multi-processor-sync-wzy"
description = "Synchronization primitives for rCore tutorial OS, including mutex, semaphore, and condvar, with SMP support."
version = "0.1.0-preview.1"
edition = "2024"
authors = ["Ziyan Wang <charliewang.cpp@gmail.com>"]
repository = "https://github.com/CharlieVinnie/tg-rcore-tutorial"
homepage = "https://github.com/CharlieVinnie/tg-rcore-tutorial/tree/smp"
documentation = "https://docs.rs/tg-rcore-tutorial-sync"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded", "concurrency"]

[dependencies]
riscv = "0.10"
spin = "0.9"
tg-task-manage = { package = "tg-rcore-tutorial-task-manage", path = "../tg-rcore-tutorial-task-manage", version = "0.4.5" }
